# SwiftLint Configuration for AxiomHiveApp

# Paths to include during linting
included:
  - AxiomHiveApp
  - AxiomHiveAppTests

# Paths to exclude from linting
excluded:
  - Pods
  - Carthage
  - fastlane
  - .build
  - DerivedData

# Disable rules
disabled_rules:
  - trailing_whitespace
  - todo

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - db
    - url
    - URL

# Custom rules
custom_rules:
  force_cast:
    name: "Force Cast"
    regex: "as!"
    match_kinds:
      - identifier
    message: "Avoid force casting. Use conditional casting instead."
    severity: warning
