app_identifier("com.axiomhive.app")
username(ENV["FASTLANE_APPLE_ID"])

price_tier(0)
app_version("1.0.0")

submission_information({
  add_id_info_limits_tracking: true,
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: false,
  add_id_info_tracks_install: false,
  content_rights_has_rights: true,
  content_rights_contains_third_party_content: false,
  export_compliance_platform: 'ios',
  export_compliance_compliance_required: false,
  export_compliance_encryption_updated: false,
  export_compliance_app_type: nil,
  export_compliance_uses_encryption: false,
  export_compliance_is_exempt: true,
  export_compliance_contains_third_party_cryptography: false,
  export_compliance_contains_proprietary_cryptography: false
})

# Metadata
metadata_path("./metadata")

# Screenshots
screenshots_path("./screenshots")

# Automatic submission settings
automatic_release(false)
submit_for_review(false)
